# async_streaming.gd
#
# async_execute_streaming() reads a large result in batches without blocking the game:
# each async_next_batch() runs on the session's I/O thread and is awaited, so frames keep
# being drawn while the rows arrive (watch the frame counter at the top). The rows are
# generated by the server itself (a recursive CTE), so this example creates no table.
#
# The Cancel button stops the read: it cancels the batch in flight (cancel()) and closes
# the cursor with async_close(), which drains the rest without blocking either.

extends Control

@onready var frame_label: Label = $Layout/Top/FrameLabel
@onready var cancel_button: Button = $Layout/Top/CancelButton
@onready var output: RichTextLabel = $Layout/Output

const ROW_COUNT := 100000
const QUERY := "WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM r WHERE n < %d) SELECT n, CONCAT('row ', n) FROM r"

var frames := 0
var started_msec := 0
var current_batch: MySQLAsyncOperation
var stop_requested := false


func _ready() -> void:
	started_msec = Time.get_ticks_msec()
	cancel_button.pressed.connect(_on_cancel_pressed)
	cancel_button.disabled = true
	await run_example()
	cancel_button.disabled = true
	DemoConfig.quit_if_headless(self)


func _process(_delta: float) -> void:
	frames += 1
	frame_label.text = "Frame %d  (%.1f s)" % [frames, (Time.get_ticks_msec() - started_msec) / 1000.0]


func run_example() -> void:
	var config := DemoConfig.load_config()
	if config == null:
		log_line("[color=red]Could not load res://config.ini. Check the Output panel below for the error.[/color]")
		return

	var session := MySQLSession.new()
	session.set_config(config)
	var err: Dictionary = session.connect_db()
	if not err.is_empty():
		log_line("[color=red]connect_db() failed: %s[/color]" % [err])
		return
	# The server stops a recursive CTE at 1000 levels by default.
	session.execute_text("SET SESSION cte_max_recursion_depth = %d" % ROW_COUNT)

	log_line("Streaming %d rows asynchronously, in batches of at least %d rows (MySQLConfig.async_batch_rows) ..." % [ROW_COUNT, config.async_batch_rows])
	var cursor := session.async_execute_streaming(QUERY % ROW_COUNT)
	cancel_button.disabled = false

	var batch_count := 0
	var row_count := 0
	while cursor.has_more():
		# Assigned and awaited in one go: nothing runs in between, so `completed` cannot
		# fire before the await starts.
		current_batch = cursor.async_next_batch()
		var batch: MySQLResult = await current_batch.completed
		current_batch = null
		if not batch.is_ok():
			log_line("[color=orange]Batch failed: %s[/color]" % [batch.get_error().get("server_message", batch.get_error().get("message", ""))])
			break
		batch_count += 1
		row_count += batch.get_rows().size()
		log_line("  Batch %d: %d rows (running total: %d), frame %d" % [batch_count, batch.get_rows().size(), row_count, frames])
		if stop_requested:
			log_line("Stopping: closing the cursor with async_close(), which drains the rest ...")
			var closed: MySQLResult = await cursor.async_close().completed
			log_line("Cursor closed (%s)." % ["ok" if closed.is_ok() else closed.get_error()])
			break
	cancel_button.disabled = true

	log_line("[color=green]Done.[/color] %d rows read in %d batches, while %d frames were drawn." % [row_count, batch_count, frames])

	# Once the cursor is read to the end or closed, the session takes other calls again.
	var after: MySQLResult = session.execute_text("SELECT 'the session is free again'")
	log_line("Next query: %s" % [after.get_rows()[0][0] if after.is_ok() else after.get_error()])
	session.close_db()


func _on_cancel_pressed() -> void:
	stop_requested = true
	cancel_button.disabled = true
	# Stops the query on the server if the batch is still waiting for it. When the rows are
	# already on their way, the batch arrives normally, and the loop closes the cursor next.
	if current_batch != null and current_batch.cancel():
		log_line("[color=orange]Cancel requested for the batch in flight.[/color]")


func log_line(text: String) -> void:
	output.append_text(text + "\n")
	print_rich(text)
