#!/usr/bin/env python
#SCsub


##### ENVIROMENT #####

Import('env')
Import("env_modules")
mysql_env = env_modules.Clone()



mysql_env.Append(CPPFLAGS=[
#	'-fexceptions',
	'-std=c++20',
])


##### PATHS #####


##### THIRDPARTY COMPILATION #####


##### GODOT MODULE #####

# INCLUDE:
mysql_env.Prepend(CPPPATH=[
#	openssl_include_path,
#	boost_include_path,
#	openssl_path
])

# LIB
env.Prepend(LIBPATH=[
#	openssl_lib_path,
#	boost_lib_path,
#	openssl_path
])

mysql_env.add_source_files(env.modules_sources, "*.cpp")
mysql_env.add_source_files(env.modules_sources, "scr/**.cpp")


env.Prepend(LIBS=["charconv", "libboost_thread", "libcrypto", "libssl"])






