-- MySQL Script generated by MySQL Workbench
-- sáb 09 dez 2023 17:55:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testes` ;
USE `testes` ;

-- -----------------------------------------------------
-- Table `testes`.`prepareted_statement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testes`.`prepareted_statement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `int_data` INT NOT NULL,
  `string_data` VARCHAR(45) NOT NULL,
  `float_data` DECIMAL NOT NULL,
  `bool_data` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testes`.`data_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testes`.`data_types` (
  `t_int` INT NOT NULL AUTO_INCREMENT,
  `t_string` VARCHAR(45) NOT NULL,
  `t_bool` TINYINT NOT NULL,
  `t_real` REAL NOT NULL,
  `t_double` DOUBLE NOT NULL,
  `t_blob` BLOB NOT NULL,
  `t_set` SET('AAAA', 'BBBB', 'CCCC', 'DDDD', 'EEEE') NOT NULL,
  `t_null` DATE NULL,
  `t_time` TIME NOT NULL,
  `t_date` DATE NOT NULL,
  `t_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`t_int`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testes`.`binary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testes`.`binary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bin` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testes`.`basic_query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testes`.`basic_query` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `string` VARCHAR(45) NOT NULL,
  `decimal` DECIMAL(5,2) NOT NULL,
  `numeric` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

